#!/bin/bash

RSYNC_VERSION=3.1.3
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg RSYNC_VERSION=$RSYNC_VERSION \
             -t $DOCKER_REPO:builder .
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg RSYNC_VERSION=$RSYNC_VERSION \
             -t $DOCKER_REPO:ssh-client rsync-ssh-client
# This is automatically pushed
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg RSYNC_VERSION=$RSYNC_VERSION \
             -t $IMAGE_NAME rsync
docker push $DOCKER_REPO:ssh-client