#!/bin/bash

RSYNC_VERSION=3.1.3
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg RSYNC_VERSION=$RSYNC_VERSION \
             -t $DOCKER_REPO:builder .
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg RSYNC_VERSION=$RSYNC_VERSION \
             -t $DOCKER_REPO:ssh-client rsync-ssh-client
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg RSYNC_VERSION=$RSYNC_VERSION \
             -t $IMAGE_NAME rsync
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg RSYNC_VERSION=$RSYNC_VERSION \
             -t $IMAGE_NAME rsync-ssh-server
# $IMAGE_NAME is automatically pushed
docker push $DOCKER_REPO:ssh-client
docker push $DOCKER_REPO:ssh-server