version: "3.7"
services:
  rsync:
    build: .
    image: qmcgaw/rsync:ssh-server
    container_name: rsync-server
    init: true
    volumes:
      - ./data:/data
      - ./ssh:/ssh
    network_mode: bridge
    ports:
      - 22:22/tcp
